# Generated by Django 3.2 on 2021-04-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookifyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
