# Generated by Django 3.2 on 2021-04-22 12:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookifyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_auto_generated_number',
            field=models.UUIDField(blank=True, null=True, verbose_name=uuid.UUID('c7e51fee-0be4-4b97-95b0-6c744ba84dfb')),
        ),
    ]
