# Generated by Django 3.2 on 2021-04-22 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookifyapp', '0002_alter_book_isbn_auto_generated_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_auto_generated_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
